In [56]:
import pandas as pd
weather = pd.read_csv("weather data.csv", index_col="DATE")
weather = weather[weather["STATION"] == "JA000047662"]

In [57]:
weather

,STATION,NAME,AWND,FMTM,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,...,WT07,WT08,WT11,WT13,WT14,WT16,WT18,WT21,WT22,WV20
DATE,,,,,,,,,,,,,,,,,,,,,
1980-01-01,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.00,NaN,NaN,42.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-02,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.04,NaN,NaN,42.0,46.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-03,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.47,NaN,NaN,46.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-04,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.45,NaN,NaN,48.0,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980-01-05,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.04,NaN,NaN,38.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-22,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.00,NaN,NaN,63.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-23,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.00,NaN,NaN,62.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-24,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.00,NaN,NaN,59.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-25,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.00,NaN,NaN,68.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-26,JA000047662,"TOKYO, JA",NaN,NaN,NaN,0.00,NaN,NaN,66.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
null_pct = weather.apply(pd.isnull).sum()/weather.shape[0]

In [59]:
null_pct

STATION    0.000000
NAME       0.000000
AWND       1.000000
FMTM       1.000000
PGTM       1.000000
PRCP       0.227433
SNOW       1.000000
SNWD       0.993805
TAVG       0.000000
TMAX       0.186358
TMIN       0.328852
WDF2       1.000000
WDFG       1.000000
WSF2       1.000000
WSFG       1.000000
WT01       1.000000
WT02       1.000000
WT03       1.000000
WT04       1.000000
WT05       1.000000
WT07       1.000000
WT08       1.000000
WT11       1.000000
WT13       1.000000
WT14       1.000000
WT16       1.000000
WT18       1.000000
WT21       1.000000
WT22       1.000000
WV20       1.000000
dtype: float64

In [60]:
valid_columns = weather.columns[null_pct<0.5]

In [61]:
valid_columns

Index(['STATION', 'NAME', 'PRCP', 'TAVG', 'TMAX', 'TMIN'], dtype='object')

In [62]:
type(weather)

pandas.core.frame.DataFrame

In [63]:
weather = weather[valid_columns].copy()

In [64]:
weather = weather.ffill()

In [65]:
weather.apply(pd.isnull).sum()

STATION    0
NAME       0
PRCP       0
TAVG       0
TMAX       0
TMIN       0
dtype: int64

In [66]:
weather.dtypes

STATION     object
NAME        object
PRCP       float64
TAVG       float64
TMAX       float64
TMIN       float64
dtype: object

In [67]:
weather.index

Index(['1980-01-01', '1980-01-02', '1980-01-03', '1980-01-04', '1980-01-05',
       '1980-01-06', '1980-01-07', '1980-01-08', '1980-01-09', '1980-01-10',
       ...
       '2025-03-17', '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21',
       '2025-03-22', '2025-03-23', '2025-03-24', '2025-03-25', '2025-03-26'],
      dtype='object', name='DATE', length=16141)

In [68]:
weather.index

Index(['1980-01-01', '1980-01-02', '1980-01-03', '1980-01-04', '1980-01-05',
       '1980-01-06', '1980-01-07', '1980-01-08', '1980-01-09', '1980-01-10',
       ...
       '2025-03-17', '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21',
       '2025-03-22', '2025-03-23', '2025-03-24', '2025-03-25', '2025-03-26'],
      dtype='object', name='DATE', length=16141)

In [69]:
weather.index = pd.to_datetime(weather.index)

In [70]:
weather.index.year.value_counts().sort_index()

DATE
1980    366
1981    365
1982    365
1983    365
1984    366
1985    365
1986    365
1987    365
1988    366
1989    365
1990    365
1991    364
1992    366
1993    365
1994    365
1995    365
1996    366
1997    365
1998    365
1999    364
2000    366
2001    365
2002    365
2003    365
2004    366
2006    365
2007    365
2008    366
2009    365
2010    365
2011    365
2012    366
2013    365
2014    365
2015    365
2016    366
2017    365
2018    365
2019    365
2020    366
2021    362
2022    365
2023    365
2024    355
2025     85
Name: count, dtype: int64

In [71]:
weather = weather.loc[~weather.index.duplicated(keep='first')]

In [72]:
print(weather.index.year.value_counts().sort_index())

DATE
1980    366
1981    365
1982    365
1983    365
1984    366
1985    365
1986    365
1987    365
1988    366
1989    365
1990    365
1991    364
1992    366
1993    365
1994    365
1995    365
1996    366
1997    365
1998    365
1999    364
2000    366
2001    365
2002    365
2003    365
2004    366
2006    365
2007    365
2008    366
2009    365
2010    365
2011    365
2012    366
2013    365
2014    365
2015    365
2016    366
2017    365
2018    365
2019    365
2020    366
2021    362
2022    365
2023    365
2024    355
2025     85
Name: count, dtype: int64

In [73]:
weather

                STATION       NAME  PRCP  TAVG  TMAX  TMIN
DATE
1980-01-01  JA000047662  TOKYO, JA  0.00  42.0  50.0  39.0
1980-01-02  JA000047662  TOKYO, JA  0.04  42.0  46.0  35.0
1980-01-03  JA000047662  TOKYO, JA  0.47  46.0  50.0  38.0
1980-01-04  JA000047662  TOKYO, JA  0.45  48.0  57.0  43.0
1980-01-05  JA000047662  TOKYO, JA  0.04  38.0  49.0  36.0
...                 ...        ...   ...   ...   ...   ...
2025-03-22  JA000047662  TOKYO, JA  0.00  63.0  57.0  44.0
2025-03-23  JA000047662  TOKYO, JA  0.00  62.0  57.0  44.0
2025-03-24  JA000047662  TOKYO, JA  0.00  59.0  57.0  50.0
2025-03-25  JA000047662  TOKYO, JA  0.00  68.0  57.0  50.0
2025-03-26  JA000047662  TOKYO, JA  0.00  66.0  57.0  50.0

[16141 rows x 6 columns]

In [74]:
weather["target"] = weather.shift(-1)["TMAX"]

In [75]:
weather

                STATION       NAME  PRCP  TAVG  TMAX  TMIN  target
DATE
1980-01-01  JA000047662  TOKYO, JA  0.00  42.0  50.0  39.0    46.0
1980-01-02  JA000047662  TOKYO, JA  0.04  42.0  46.0  35.0    50.0
1980-01-03  JA000047662  TOKYO, JA  0.47  46.0  50.0  38.0    57.0
1980-01-04  JA000047662  TOKYO, JA  0.45  48.0  57.0  43.0    49.0
1980-01-05  JA000047662  TOKYO, JA  0.04  38.0  49.0  36.0    53.0
...                 ...        ...   ...   ...   ...   ...     ...
2025-03-22  JA000047662  TOKYO, JA  0.00  63.0  57.0  44.0    57.0
2025-03-23  JA000047662  TOKYO, JA  0.00  62.0  57.0  44.0    57.0
2025-03-24  JA000047662  TOKYO, JA  0.00  59.0  57.0  50.0    57.0
2025-03-25  JA000047662  TOKYO, JA  0.00  68.0  57.0  50.0    57.0
2025-03-26  JA000047662  TOKYO, JA  0.00  66.0  57.0  50.0     NaN

[16141 rows x 7 columns]

In [76]:
from sklearn.linear_model import Ridge
regression = Ridge(alpha=0.1)

In [77]:
predictors = weather.columns[~weather.columns.isin(["target", "STATION", "NAME"])]
predictors = [col for col in weather.columns if col not in ["DATE", "target"]]

predictors = weather.select_dtypes(include=["float64"]).drop(columns=["target"]).columns

In [78]:
predictors

Index(['PRCP', 'TAVG', 'TMAX', 'TMIN'], dtype='object')

In [79]:
def backtest(weather, model, predictors, start =3650, step = 30):
    all_predictions = []

    for i in range(start, weather.shape[0], step):
        train = weather.iloc[:i, :]
        test = weather.iloc[i: i+step, :]

        model.fit(train[predictors], train ["target"])

        preds = model.predict(test[predictors])

        preds = pd.Series(preds, index = test.index)
        combined = pd.concat([test["target"], preds], axis=1)

        combined.columns = ["actual", "predictions"]

        combined["diff"] = (combined["predictions"] - combined["actual"]).abs()

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [80]:
predictions = backtest(weather, regression, predictors)

In [81]:
predictions

            actual  predictions      diff
DATE
1989-12-29    51.0    53.864930  2.864930
1989-12-30    50.0    51.243134  1.243134
1989-12-31    50.0    49.010518  0.989482
1990-01-01    49.0    47.699620  1.300380
1990-01-02    48.0    49.430323  1.430323
...            ...          ...       ...
2025-03-22    57.0    57.040595  0.040595
2025-03-23    57.0    57.077437  0.077437
2025-03-24    57.0    57.994208  0.994208
2025-03-25    57.0    57.662628  0.662628
2025-03-26     NaN    57.736312       NaN

[12491 rows x 3 columns]

In [82]:
weather.reset_index(inplace=True)

In [83]:
predictions["diff"].mean()

np.float64(3.9687520151548705)